apiVersion: apps/v1
kind: Deployment
metadata:
  name: ?module_name-deployment
  labels:
    app: ?module_name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ?module_name
  template:
    metadata:
      labels:
        app: ?module_name
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: ?module_name
        image: ?image_path
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ?module_name-service
spec:
  selector:
    app: ?module_name
  ports:
    - protocol: HTTP
      targetPort: 80
          nodePort: 29999
  type: NodePort
